- 👋 Hi, I’m @Statoshinakomoto2002
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...
bitcoin 2009creator developer Genesis block
<!---
Statoshinakomoto2002/Statoshinakomoto2002 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
